openapi: 3.2.0
info:
  title: LeanData and Round Robin Matching API
  description: Real-time Salesforce-native matching and routing via the LeanData managed package Apex REST endpoint. Includes lead/contact/account matching, duplicate detection, related-record lookups, and round-robin assignment.
  version: 1.0.0
servers:
- url: https://yourinstance.my.salesforce.com
tags:
- name: Matching
paths:
  /services/apexrest/LeanData/LeanDataAPI:
    post:
      tags:
      - Matching
      summary: One Time Routing
      description: 'Purpose: Runs one-time routing via a specified graph on a set of standard objects (Lead, Contact, Account, Opportunity, Case) based on SOQL query


        Required Body Params:


        @param ''requesterName'' Name of the API caller


        @param ''apiType'' Type of API call


        @param ''version'' LeanData API version (should be 2)


        @param ''objectType'' Type of object to route


        @param ''condition'' SOQL condition to query i.e. Title = ''CEO''


        @param ''graphName'' Name of the graph to use for 1x Routing


        @param ''notificationsDisabled'' Disables all notifications from 1x Routing


        @param ''nodeType'' ''Trigger'' or ''Update Trigger'' to enter from Insert Or Update Trigger Nodes respectively


        @param ''edgeName'' Name of edge from Trigger Node e.g. ''Lead is MQL''


        Optional Body Params:


        @param ''allowDedupe'' Flag to allow deduplication. Value will by false by default


        @param ''businessUnitId'' Id of the specific business unit graph to route the object through. Value will by null by default


        @param ''orderBy'' sort records that are found from SOQL condition (i.e. "CreatedDate DESC")


        @param ''queryLimit'' limit the records found from SOQL condition


        @param ''respectSchedules'' Route records only to available users


        Available in version 1.500+ of LeanData'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                requesterName: LeanData
                apiType: routing
                operation: oneTime
                version: '2'
                objectType: Lead
                condition: Title ='CEO'
                graphName: Test Routing Api
                notificationsDisabled: false
                sendEmail: true
                nodeType: Update Trigger
                edgeName: Lead is MQL
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
        example: Bearer {{sessionid}}
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: postServicesApexrestLeanDataLeanDataAPI
      x-operation-id-source: derived
